import type { Track } from "./types";

export const demoTracks: Track[] = [
  {
    id: "deep-reflection",
    title: "Nureha no kei (Deep Reflection Remix)",
    artist: "Clean Tears & Hatsune Miku",
    album: "Deep Reflection",
    duration: 437,
    mood: "Relax",
    type: "Song",
    colorA: "#8db7e8",
    colorB: "#32446d",
    colorC: "#dfe8ff",
    source: "demo",
    lyrics: [
      [0, "静かな夜"],
      [28, "shizuka na yoru"],
      [56, "幾つもの星たちが"],
      [118, "波に揺られては泳いでいく"],
      [196, "さざ波に浮かぶ舟"],
      [286, "二人言葉無く"],
      [384, "優しく月の光は"],
    ],
  },
  {
    id: "signal-bloom",
    title: "Signal Bloom",
    artist: "Tala North",
    album: "Night archive",
    duration: 246,
    mood: "Focus",
    type: "Song",
    colorA: "#ed5564",
    colorB: "#6f2431",
    colorC: "#f6c0c7",
    source: "demo",
    lyrics: [
      [0, "A red dial wakes in the quiet"],
      [18, "Static folds into a line"],
      [67, "Every pulse repeats your sign"],
      [96, "Signal bloom, carry me closer"],
      [164, "Signal bloom, keep the night open"],
      [202, "I can hear the morning tune"],
    ],
  },
  {
    id: "monsoon-arcade",
    title: "Monsoon Arcade",
    artist: "Luma Veda",
    album: "Streetlight weather",
    duration: 218,
    mood: "Energize",
    type: "Song",
    colorA: "#51d0bf",
    colorB: "#276d95",
    colorC: "#d7fff7",
    source: "demo",
    lyrics: [
      [0, "Coins on the counter, rain on the wires"],
      [24, "Neon runs down the lane"],
      [83, "Finding our names in the rain"],
      [118, "Monsoon arcade, light up the water"],
      [185, "The city is singing in color"],
    ],
  },
  {
    id: "glass-temple",
    title: "Glass Temple",
    artist: "Niko Sable",
    album: "Soft machines",
    duration: 231,
    mood: "Focus",
    type: "Song",
    colorA: "#9da8ff",
    colorB: "#3c3b88",
    colorC: "#edf0ff",
    source: "demo",
    lyrics: [
      [0, "Steps ring clear in the glass temple"],
      [59, "I leave the door open behind me"],
      [127, "Hold the note, let it assemble"],
      [202, "Glass temple, glass temple"],
    ],
  },
];

export const moods: Array<[string, string, string]> = [
  ["Feel good", "#f06292", "#8e244d"],
  ["Energize", "#ffb74d", "#ad5a18"],
  ["Relax", "#81c784", "#28664c"],
  ["Commute", "#64b5f6", "#315d91"],
  ["Focus", "#9575cd", "#443170"],
  ["Workout", "#ef5350", "#8b2025"],
  ["Sleep", "#90a4ae", "#35454f"],
  ["Romance", "#f48fb1", "#8a3156"],
];
